// <auto-generated />
namespace Lumio.Engine.NativeLoader;

internal static class AbiConstants
{
    public const uint AbiVersion = 1;
    public const string EntrySymbol = "lumio_engine_get_api_v1";
    public const string DefinitionSha256 = "9542e15a2ee2e93a4db3656f119e39a109ca0e6a6d7df2653d09561200748d4d";
}
