<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Lumio.Engine.NativeLoader</AssemblyName>
    <RootNamespace>Lumio.Engine.NativeLoader</RootNamespace>
  </PropertyGroup>
</Project>
