// Generated by eng/generate-abi.mjs. Do not edit.

pub const ABI_VERSION: u32 = 1;
pub const ENTRY_SYMBOL: &str = "lumio_engine_get_api_v1";
pub const DEFINITION_SHA256: &str = "ee2f6c6dc2e73a58561ba82325bc1c7c12fbfee52e94e9466642bd0a38510a41";
