[package]
name = "lumio-engine-native"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
lumio-kernel = { path = "../../../../../LumioNativeCore/crates/lumio-kernel" }
lumio-voxel-world = { path = "../../../../../LumioVoxelEngine/crates/lumio-voxel-world" }

[dev-dependencies]
