import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const definitionPath = resolve(root, 'engine/abi/native-abi.json');
const definitionBytes = await readFile(definitionPath);
const definition = JSON.parse(definitionBytes);
const definitionHash = createHash('sha256').update(definitionBytes).digest('hex');
const abiVersion = Number(definition.abiVersion);
const entrySymbol = String(definition.entrySymbol);

if (!Number.isInteger(abiVersion) || abiVersion < 1) {
  throw new Error('native-abi.json abiVersion must be a positive integer');
}
if (!/^lumio_[a-z0-9_]+_v\d+$/.test(entrySymbol)) {
  throw new Error(`invalid entrySymbol: ${entrySymbol}`);
}

const rustPath = resolve(root, 'engine/native/modules/sdk-native/src/abi_generated.rs');
const csharpPath = resolve(root, 'engine/managed/Lumio.Engine.NativeLoader/AbiConstants.g.cs');
await mkdir(dirname(rustPath), { recursive: true });
await mkdir(dirname(csharpPath), { recursive: true });

await writeFile(rustPath, `// Generated by eng/generate-abi.mjs. Do not edit.\n\npub const ABI_VERSION: u32 = ${abiVersion};\npub const ENTRY_SYMBOL: &str = "${entrySymbol}";\npub const DEFINITION_SHA256: &str = "${definitionHash}";\n`, 'utf8');
await writeFile(csharpPath, `// <auto-generated />\nnamespace Lumio.Engine.NativeLoader;\n\ninternal static class AbiConstants\n{\n    public const uint AbiVersion = ${abiVersion};\n    public const string EntrySymbol = "${entrySymbol}";\n    public const string DefinitionSha256 = "${definitionHash}";\n}\n`, 'utf8');

console.log(`ABI_VERSION=${abiVersion}`);
console.log(`ENTRY_SYMBOL=${entrySymbol}`);
console.log(`DEFINITION_SHA256=${definitionHash}`);
